# Derek Sandefur
## Week 12 - 4/4/2024
### Python NumPy Universal Functions

In [1]:
# Universal functions are a powerfull tool
# for performing mathematical operations on NumPy arrays, ndarray.
# This makes them much faster than looping over
# the elements of an array and performing the operation manually.
import numpy as np

arr = np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [2]:
# sqrt
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [3]:
#exp()
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [4]:
#randn - Generates standard normal distribution sample.
arr = np.random.randn(10)
arr

array([ 0.40623244, -2.98922294,  0.91018832,  1.27358224,  1.6869154 ,
       -0.51933508, -0.15910028,  0.66931263, -0.28808422,  0.0639265 ])

In [5]:
arr = np.random.randn(20)
arr

array([ 0.18233834,  1.11865685, -0.51635635,  0.51632099,  0.58542987,
       -0.25463517, -0.84784807,  0.1746653 ,  0.30044771,  1.50254421,
        0.08920173,  1.16197597,  0.95701365, -0.44315815, -1.72681125,
        0.96725667, -1.25661851, -0.47542393, -0.21081703,  1.00185938])

In [6]:
arr1 = np.random.randn(10)
arr1

array([ 0.41754272, -0.66265309, -0.722354  ,  0.57388445,  1.53155846,
        0.48456774, -0.63549707,  0.16296174, -0.57210037,  0.71085969])

In [7]:
arr2 = np.random.randn(10)
arr2

array([ 0.3375298 ,  0.86953345, -2.40633276,  0.52954276, -0.71115103,
        0.79100357, -0.4046614 ,  1.56239227, -1.25127639,  0.69185175])

In [8]:
np.add(arr1,arr2)

array([ 0.75507252,  0.20688036, -3.12868676,  1.10342721,  0.82040744,
        1.27557131, -1.04015847,  1.72535401, -1.82337676,  1.40271144])

In [9]:
# maximum
np.maximum(arr1,arr2)

array([ 0.41754272,  0.86953345, -0.722354  ,  0.57388445,  1.53155846,
        0.79100357, -0.4046614 ,  1.56239227, -0.57210037,  0.71085969])

In [10]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
arr2 = np.ones(9).reshape(3,3)
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.add(arr1,arr2)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [13]:
# Array filtering
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
arr > 4

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [15]:
# where
# replace values of an array, using where
# Return elements chosen from 'x' or 'y' depending on 'condition'
np.where(arr>4, arr,0)

array([[0, 0, 0],
       [0, 0, 5],
       [6, 7, 8]])

In [16]:
np.where(arr < 4, arr, 0)

array([[0, 1, 2],
       [3, 0, 0],
       [0, 0, 0]])

In [17]:
from numpy.random import randn
arr = randn(3,3)
arr

array([[ 1.21396888, -0.42559314,  0.48288555],
       [-0.0356957 ,  1.54857958,  0.30738096],
       [ 0.33474169, -0.30201651, -0.87491283]])

In [18]:
np.where(arr<0,0,arr)

array([[1.21396888, 0.        , 0.48288555],
       [0.        , 1.54857958, 0.30738096],
       [0.33474169, 0.        , 0.        ]])

In [19]:
np.where([True,False,True,False], 1,0)

array([1, 0, 1, 0])

In [20]:
sample_bool_arr = [True,False]
arr_bool = np.random.choice(sample_bool_arr, size=10)
arr_bool

array([ True, False,  True, False, False,  True,  True,  True, False,
       False])

In [21]:
arr1 = np.arange(1,6)
arr2 = arr1*10
arr_bool = np.random.choice(sample_bool_arr, size=5)

In [22]:
arr1

array([1, 2, 3, 4, 5])

In [23]:
arr2

array([10, 20, 30, 40, 50])

In [24]:
arr_bool

array([ True, False, False, False, False])

In [25]:
np.where(arr_bool,arr1,arr2)

array([ 1, 20, 30, 40, 50])

In [28]:
[r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_bool)]

[1, 20, 30, 40, 50]

In [29]:
list(zip(arr1,arr2,arr_bool))

[(1, 10, True), (2, 20, False), (3, 30, False), (4, 40, False), (5, 50, False)]

In [39]:
# using where with 2-D array
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
arr_bool = np.array([[np.random.choice(sample_bool_arr, size=2)], [np.random.choice(sample_bool_arr, size=4)]])

In [40]:
arr1

array([[1, 2],
       [3, 4]])

In [41]:
arr2

array([[5, 6],
       [7, 8]])

In [42]:
arr_bool

array([[array([False, False])],
       [array([ True, False, False, False])]], dtype=object)

In [43]:
arr_bool = np.random.choice(sample_bool_arr, size=4).reshape(2,2)
arr_bool

array([[ True,  True],
       [False, False]])

In [44]:
np.where(arr_bool,arr1,arr2)

array([[1, 2],
       [7, 8]])

In [45]:
# any - Returns True if any of the elements of 'a' evaluate to True.
arr_bool = np.random.choice(sample_bool_arr, size=5)
arr_bool

array([False,  True,  True, False, False])

In [46]:
arr_bool.any()

True

In [47]:
# all
arr_bool.all()

False

In [48]:
# unique()
fruits = np.array(['Apple','Cherry','Apple', 'Orange', 'Cherry','Banana'])
np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [49]:
#in1d
np.in1d(['Apple','Cherry','Grape'],fruits)

array([ True,  True, False])

In [50]:
# Descriptive Statistical Measures
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr.shape

(3, 3)

In [52]:
arr.sum()

45

In [53]:
arr.sum(0)

array([12, 15, 18])

In [54]:
arr.sum(1) #axis0

array([ 6, 15, 24])

In [55]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [56]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [57]:
arr.mean()

5.0

In [58]:
arr.mean(0) #axis0

array([4., 5., 6.])

In [59]:
arr.mean(1) #axis1

array([2., 5., 8.])

In [60]:
np.mean(arr,axis=0)

array([4., 5., 6.])

In [62]:
np.mean(arr,axis=1)

array([2., 5., 8.])

In [63]:
arr.var()

6.666666666666667

In [64]:
arr.std()

2.581988897471611

In [65]:
arr = np.array([2,5,1,8,3,5,8,9,2,3,4,6,7])
arr.sort()

In [66]:
arr

array([1, 2, 2, 3, 3, 4, 5, 5, 6, 7, 8, 8, 9])

In [67]:
# Random - Different random [0.0,1.0]
arr = np.random.random((4,4))
arr

array([[0.58470161, 0.14233764, 0.38178809, 0.27511914],
       [0.00376561, 0.57226507, 0.38178336, 0.7200491 ],
       [0.19608869, 0.05802   , 0.61358465, 0.77266417],
       [0.92287417, 0.17405543, 0.42384312, 0.04953854]])

In [68]:
np.random.randint(10,50)

42

In [69]:
# concatenate or join arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6])