# Derek Sandefur
## Week 12 - 4/2/2024
### Python numpy creating, processing, transporting arrays

In [1]:
import numpy as np

In [2]:
arr_2d = np.arange(1,9).reshape(2,4)
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
arr_3d = np.arange(1,9).reshape(2,2,2)
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [4]:
print(arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# Pass -1 as the value, and NumPy will calculate this number for you.
arr_2d = np.arange(1,9).reshape(2,-1)
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr_2d = np.arange(1,9).reshape(-1,4)
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr_2d.shape

(2, 4)

In [8]:
arr_3d = np.arange(1,25).reshape(2,3,-1)
arr_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [9]:
arr_3d.shape

(2, 3, 4)

In [10]:
arr_3d = np.arange(1,25).reshape(2,-1,2)
arr_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [11]:
arr_3d.shape

(2, 6, 2)

In [12]:
arr_3d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [13]:
arr_3d.reshape(-1,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [14]:
#Iterating Arrays
arr_1d = arr_3d.reshape(-1)
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [15]:
for n in arr_1d:
    print(n, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 

In [17]:
#2d array
for n in arr_2d:
    print(n)

[1 2 3 4]
[5 6 7 8]


In [18]:
for arr in arr_2d:
    for n in arr:
        print(n, end=' ')

1 2 3 4 5 6 7 8 

In [19]:
# 3d array
for r_2d in arr_3d:
    for r_1d in r_2d:
        for n in r_1d:
            print(n, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 

In [20]:
#nditer interates on each scalar element in the np array
for n in np.nditer(arr_3d):
    print(n, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 

In [21]:
for n in np.nditer(arr_2d):
    print(n, end=' ')

1 2 3 4 5 6 7 8 

In [22]:
#Multidimensional index iterator.
# ndenumerate()
for i, n in np.ndenumerate(arr_1d):
    print(i,n)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10
(10,) 11
(11,) 12
(12,) 13
(13,) 14
(14,) 15
(15,) 16
(16,) 17
(17,) 18
(18,) 19
(19,) 20
(20,) 21
(21,) 22
(22,) 23
(23,) 24


In [23]:
for i, n in np.ndenumerate(arr_2d):
    print(i,n)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [24]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
arr_2d[1,1]

6

In [26]:
for i, n in np.ndenumerate(arr_3d):
    print(i,n)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(0, 2, 0) 5
(0, 2, 1) 6
(0, 3, 0) 7
(0, 3, 1) 8
(0, 4, 0) 9
(0, 4, 1) 10
(0, 5, 0) 11
(0, 5, 1) 12
(1, 0, 0) 13
(1, 0, 1) 14
(1, 1, 0) 15
(1, 1, 1) 16
(1, 2, 0) 17
(1, 2, 1) 18
(1, 3, 0) 19
(1, 3, 1) 20
(1, 4, 0) 21
(1, 4, 1) 22
(1, 5, 0) 23
(1, 5, 1) 24


In [27]:
arr_3d[1, 1, 0]

15

In [28]:
arr_3d.shape

(2, 6, 2)

In [29]:
arr_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [30]:
# operations *, +, -, /
arr_2d * arr_2d

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [31]:
arr_2d + arr_2d

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [32]:
arr_2d - arr_2d

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [33]:
1 / arr_2d

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [34]:
arr_2d**2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]], dtype=int32)

In [35]:
# .T Same as self,transpose(), except that self is returned in self.ndim < 2.
# Returns the transpose of the matrix.
# transpose. Reverse or permute the axes of the array; returns the modified array.
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
arr_2d.shape

(2, 4)

In [37]:
arr_2d.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [38]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
t = arr_2d.T
t

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [40]:
t.shape

(4, 2)

In [41]:
arr_2d[0] = 100
arr_2d

array([[100, 100, 100, 100],
       [  5,   6,   7,   8]])

In [42]:
t

array([[100,   5],
       [100,   6],
       [100,   7],
       [100,   8]])

In [43]:
arr_2d = np.arange(45).reshape(5,9)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [45]:
t = arr_2d.T
t

array([[ 0,  9, 18, 27, 36],
       [ 1, 10, 19, 28, 37],
       [ 2, 11, 20, 29, 38],
       [ 3, 12, 21, 30, 39],
       [ 4, 13, 22, 31, 40],
       [ 5, 14, 23, 32, 41],
       [ 6, 15, 24, 33, 42],
       [ 7, 16, 25, 34, 43],
       [ 8, 17, 26, 35, 44]])

In [48]:
arr_2d[:3] = 100
arr_2d

array([[100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44]])

In [49]:
t

array([[100, 100, 100,  27,  36],
       [100, 100, 100,  28,  37],
       [100, 100, 100,  29,  38],
       [100, 100, 100,  30,  39],
       [100, 100, 100,  31,  40],
       [100, 100, 100,  32,  41],
       [100, 100, 100,  33,  42],
       [100, 100, 100,  34,  43],
       [100, 100, 100,  35,  44]])

In [51]:
t[:,-1] = 100
t

array([[100, 100, 100,  27, 100],
       [100, 100, 100,  28, 100],
       [100, 100, 100,  29, 100],
       [100, 100, 100,  30, 100],
       [100, 100, 100,  31, 100],
       [100, 100, 100,  32, 100],
       [100, 100, 100,  33, 100],
       [100, 100, 100,  34, 100],
       [100, 100, 100,  35, 100]])

In [52]:
arr_3d = np.arange(1,21).reshape(-1,5,4)
arr_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]])

In [53]:
arr_3d.shape

(1, 5, 4)

In [54]:
arr_3d.T

array([[[ 1],
        [ 5],
        [ 9],
        [13],
        [17]],

       [[ 2],
        [ 6],
        [10],
        [14],
        [18]],

       [[ 3],
        [ 7],
        [11],
        [15],
        [19]],

       [[ 4],
        [ 8],
        [12],
        [16],
        [20]]])

In [55]:
arr_3d.T.shape

(4, 5, 1)

In [56]:
# transpose
arr_2d = np.arange(1,7).reshape(2,3)
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
t = np.transpose(arr_2d)
t

array([[1, 4],
       [2, 5],
       [3, 6]])

In [60]:
t.shape

(3, 2)

In [61]:
arr_3d = np.arange(20).reshape(2,5,2)
arr_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [62]:
arr_3d.T

array([[[ 0, 10],
        [ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18]],

       [[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]]])

In [63]:
arr_3d.T.shape

(2, 5, 2)

In [64]:
np.transpose(arr_3d)

array([[[ 0, 10],
        [ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18]],

       [[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]]])

In [65]:
arr_3d.transpose()

array([[[ 0, 10],
        [ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18]],

       [[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]]])

In [66]:
arr_3d.transpose((0,1,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [67]:
arr_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [68]:
arr_3d.shape

(2, 5, 2)

In [69]:
arr_3d.transpose((0,2,1))

array([[[ 0,  2,  4,  6,  8],
        [ 1,  3,  5,  7,  9]],

       [[10, 12, 14, 16, 18],
        [11, 13, 15, 17, 19]]])

In [70]:
arr_3d.transpose((0,2,1)).shape

(2, 2, 5)

In [71]:
arr_3d.transpose((0,2,1)).shape[0]

2

In [72]:
arr_3d.transpose((0,2,1)).shape[1]

2

In [73]:
arr_3d.transpose((0,2,1)).shape[2]

5

In [74]:
arr_3d.transpose((2,0,1))

array([[[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18]],

       [[ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19]]])

In [75]:
#swapaxes
arr_3d = np.arange(24).reshape(2,3,4)
arr_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [76]:
arr_3d.shape

(2, 3, 4)

In [77]:
arr_3d.swapaxes(0,1)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [78]:
arr_3d.swapaxes(0,1).shape

(3, 2, 4)

In [79]:
#(4,3,2)
arr_3d.swapaxes(0,2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [80]:
arr_3d.swapaxes(0,2).shape

(4, 3, 2)